---
- id: tf-fmt
  name: Terraform fmt
  entry: hooks/tf-fmt.sh
  language: script
  files: \.tf$
  exclude: \.+.terraform\/.*$
  require_serial: true

- id: tflint
  name: tflint
  description: Linter for Terraform source code
  entry: hooks/tflint.sh
  language: script
  files: \.tf$
  exclude: \.+.terraform\/.*$

- id: tf-checkov
  name: checkov
  description: Runs checkov on Terraform resourcecs
  entry: hooks/tf_checkov.sh
  language: script
  always_run: false
  files: \.tf$
  exclude: \.terraform\/.*$
  require_serial: true

- id: trivy
  name: trivy
  description: Scans for misconfigurations, vulnerabilities and secrets.
  require_serial: true
  entry: hooks/trivy.sh
  language: script

- id: tf-validate
  name: Terraform validation
  entry: hooks/tf-validate.sh
  language: script
  files: \.tf$
  exclude: \.+.terraform\/.*$
  require_serial: true

- id: yamllint
  name: yamllint
  entry: hooks/yamllint.sh
  language: script
  files: \.ya?ml$
  require_serial: true

- id: go-fmt
  name: gofmt
  entry: hooks/go-fmt.sh
  language: script
  files: \.go$
  exclude: vendor\/.*$

- id: golangci-lint
  name: golangci-lint
  entry: hooks/golangci-lint.sh
  types: [go]
  language: script
  require_serial: true
  pass_filenames: true

- id: go-unit-tests
  name: go unit tests
  entry: hooks/go-unit-tests.sh
  types: [go]
  language: script
  require_serial: true
  pass_filenames: false

- id: shellcheck
  name: Shellcheck
  entry: hooks/shellcheck.sh
  language: script
  types:
    - shell

- id: conventional-commit
  name: Conventional commit checker
  entry: hooks/conventional-commit.sh
  language: script
  description: Check whether commit messages comply with the conventional commit format
  always_run: true
  stages:
    - commit-msg

- id: pylint
  name: pylint
  entry: hooks/pylint.sh
  language: script
  files: \.py$
