---
- id: tf-fmt
  name: Terraform fmt
  entry: hooks/tf-fmt.sh
  language: script
  files: \.tf$
  exclude: \.+.terraform\/.*$
  require_serial: true

- id: tf-validate
  name: Terraform validation
  entry: hooks/tf-validate.sh
  language: script
  files: \.tf$
  exclude: \.+.terraform\/.*$
  require_serial: true

- id: yamllint
  name: yamllint
  entry: hooks/yamllint.sh
  language: script
  files: \.ya?ml$

- id: go-fmt
  name: gofmt
  entry: hooks/go-fmt.sh
  language: script
  files: \.go$
  exclude: vendor\/.*$

- id: golangci-lint
  name: golangci-lint
  entry: golangci-lint run --timeout=5m
  types: [go]
  language: golang
  require_serial: true
  pass_filenames: false

- id: go-unit-tests
  name: go unit tests
  entry: go test -race ./...
  types: [go]
  language: golang
  require_serial: true
  pass_filenames: false

- id: shellcheck
  name: Shellcheck
  entry: hooks/shellcheck.sh
  language: script
  types:
    - shell

- id: conventional-commit
  name: Conventional commit
  entry: hooks/conventional-commit.sh
  language: script
  description: Check whether commit messages comply with the conventional commit format
  always_run: true
  stages:
    - commit-msg

- id: pylint
  name: pylint
  entry: hooks/pylint.sh
  language: script
  files: \.py$
